apiVersion: v1
kind: Service
metadata:
  name: halyard-sockets
  labels:
    app: halyard
    component: sockets
spec:
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999
  selector:
    app: halyard
    component: sockets