apiVersion: apps/v1
kind: Deployment
metadata:
  name: halyard-database
  labels:
    app: halyard
    component: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard
      component: database

  template:
    metadata:
      labels:
        app: halyard
        component: database

    spec:
      containers:
        - name: mongodb-container
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: halyard-database
          ports:
            - containerPort: 27017