apiVersion: v1
kind: Service
metadata:
  name: halyard-frontend
  labels:
    app: halyard
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - name: unsecure
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: halyard
    component: frontend
