apiVersion: v1
kind: Service
metadata:
  name: halyard-echo
  labels:
    app: halyard
    component: echo
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: halyard
    component: echo