apiVersion: v1
kind: Service
metadata:
  name: halyard-sails
  labels:
    app: halyard
    component: sails
spec:
  type: LoadBalancer
  ports:
    - name: unsecure
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: halyard
    component: sails
