apiVersion: system.codezero.io/v1
kind: App
name: halyard-database
appId: halyard-database
package: '@provisioner/appengine'
editions:
  - name: stable
    status: private
    spec:
      routes:
        - type: http
          targetService: halyard-database
      provisioner:
        tag-prefix: appengine
        package: '@provisioner/appengine'
        image: 'mongo:4.4.5'
        ports: 27017
#        env:
#          - name: MONGO_INITDB_DATABASE
#            value: halyard-database
        config:
        - halyard-database:
            user: testUser
            password: password
            roles:
              - readWrite
            secretKey: HALYARD_DATABASE
            secretKeyRef:
              name: mariadb-root
              key: {{rootPasswordKey}}
      marina:
        launch:
          type: inline
          popUp: false