apiVersion: system.codezero.io/v1
kind: Environment
metadata:
  name: front-end-dev
spec:
  services:
    halyard-database:
      fromFile: ../apps/halyard-database.yaml
    halyard-echo:
      fromFile: ../apps/halyard-echo.yaml
      await: halyard-database
    halyard-backend:
      fromFile: ../apps/halyard-backend.yaml
      await: halyard-echo
    halyard-frontend: local